# CS 20: TensorFlow for Deep Learning - Lecture 2

In [4]:
import tensorflow as tf

### Visualize with TensorBoard

In [9]:
# specify names of each one
a = tf.constant(3, name = "a")
b = tf.constant(4, name = "b")
x = tf.add(a, b, name = "add")
with tf.Session() as sess:
    # writer for writing tensor graph to local folder
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
writer.close()

7


### tf.constant
tf.constant(value, dtype=None, shape=None, name="Const", verify_shape=False)
- if verify_shape is not set, and value is different from given shape, it fills its last number to empty fields of the shape.

In [14]:
a = tf.constant(2, shape=[2,2])
b = tf.constant([2, 1], shape=[3, 3])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[2 2]
 [2 2]]
[[2 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
# broadcast happens
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
with tf.Session() as sess:
    x, y = sess.run([x, y])
print(x)
print(y)

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]


## Tensors filled with a specific value
### tf.zeros()
- tf.zeros(shape, dtype=tf.float32, name=None)
- tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)

### tf.ones()
- tf.ones(shape, dtype=float32, name=None)
- tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)

### tf.fill()
tf.fill(dim, value, name=None)

In [23]:
a = tf.zeros([2, 3], tf.int32)
b = tf.zeros_like()
print(a)
tf.fill([2, 3], 8)

Tensor("zeros_1:0", shape=(2, 3), dtype=int32)


<tf.Tensor 'Fill_2:0' shape=(2, 3) dtype=int32>