# CS 20: TensorFlow for Deep Learning - Lecture 2

In [31]:
import tensorflow as tf
import numpy as np

### Visualize with TensorBoard

In [9]:
# specify names of each one
a = tf.constant(3, name = "a")
b = tf.constant(4, name = "b")
x = tf.add(a, b, name = "add")
with tf.Session() as sess:
    # writer for writing tensor graph to local folder
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
writer.close()

7


### tf.constant
tf.constant(value, dtype=None, shape=None, name="Const", verify_shape=False)
- if verify_shape is not set, and value is different from given shape, it fills its last number to empty fields of the shape.

In [14]:
a = tf.constant(2, shape=[2,2])
b = tf.constant([2, 1], shape=[3, 3])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[2 2]
 [2 2]]
[[2 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
# broadcast happens
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
with tf.Session() as sess:
    x, y = sess.run([x, y])
print(x)
print(y)

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]


## Tensors filled with a specific value
### tf.zeros()
- tf.zeros(shape, dtype=tf.float32, name=None)
- tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)

### tf.ones()
- tf.ones(shape, dtype=float32, name=None)
- tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)

### tf.fill()
tf.fill(dim, value, name=None)

In [27]:
a = tf.zeros([2, 3], tf.int32)
input_tensor = tf.constant([[0, 1], [2, 3]])
b = tf.zeros_like(input_tensor)
c = tf.fill([2, 3], 8)
with tf.Session() as sess:
    a, b, c = sess.run([a, b, c])
print(a)
print(b)
print(c)


[[0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]]
[[8 8 8]
 [8 8 8]]


## Constant as sequences

### tf.linspace()
tf.linspace(start, stop, num, name=None)
### tf.range()
tf.range(start, limit, delta=1, dtype=None, name='range')

In [28]:
a = tf.linspace(10.0, 13.0, 4)
b = tf.range(3, 18, 3)
c = tf.range(5)
with tf.Session() as sess:
    print(sess.run([a, b, c]))

[array([10., 11., 12., 13.], dtype=float32), array([ 3,  6,  9, 12, 15], dtype=int32), array([0, 1, 2, 3, 4], dtype=int32)]


## Randomly generated constants
### tf.random_normal()
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
### tf.truncated_normal()
tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
### tf.random_uniform()
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
### tf.random_shuffle()
tf.random_shuffle(value, seed=None, name=None)

- shuffling in the first dimension

### tf.random_crop()
tf.random_crop(value, size, seed=None, name=None)
### tf.multinomial()
tf.multinomial(logits, num_samples, seed=None, name=None)
### tf.random_gamma()
tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)

### tf.set_random_seed(seed)
Set a constant seed such that the program is deterministic random, results can be the same each run.

In [37]:
a = tf.constant([[2,1], [2,2], [3,3]])
an = tf.random_shuffle(a)

b = tf.constant(np.random.normal(size=(3,4)))
bn = tf.multinomial(b, 5)

c = tf.random_gamma([10], 5)
with tf.Session() as sess:
    x, y, z = sess.run([an, bn, c])
print(x)
print(y)
print(z)

[[2 2]
 [2 1]
 [3 3]]
[[2 2 2 1 1]
 [0 3 0 3 0]
 [2 3 1 3 1]]
[4.0433626 1.9850466 4.9746246 5.486055  3.204046  3.632511  5.3459353
 2.0519083 3.0139163 6.4759774]


## TensorFlow Data Types
- Tensorflow takes python native types: boolean, int, float, strings
- Seamlessly with NumPy
- Do not use python native types, need infering
- In the future, numpy and tensorflow may not be compatible
- NumPy is not GPU compatible

In [46]:
a = tf.int32 == np.int32
print(a)

b = tf.ones([2, 2], tf.float32)
with tf.Session() as sess:
    y = sess.run(b)    
print(type(b))
print(type(y))

True
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.ndarray'>


In [47]:
my_const = tf.constant([1.0, 2.0], name="my_const")
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 4
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Add/x"
  input: "Add/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Add_1/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add_1/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
 

## Variables
- if the data to stored is large, instead of using constant, use variables

- x = tf.Variable()
- x.initializer
- x.value()
- x.assign()
- x.assign_add()

In [51]:
a = tf.Variable(2, name="scalar")
b = tf.Variable([2, 3], name="vector")
c = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))


# Init all variables
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
# Init only a subset of variables
init_ab = tf.variables_initializer([a, b], name="init_ab")
with tf.Session() as sess:
    sess.run(init_ab)
    print(a.eval())
    
# Init a single varaible
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

2
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [55]:
W = tf.Variable(10)
assign_op = W.assign(100) # if not called inside session, value will not be changed
with tf.Session() as sess:
    sess.run(W.initializer) # can be ignored if assign_op is run.
    sess.run(assign_op)
    print(W.eval())

100


In [56]:
my_var = tf.Variable(10)
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var.assign_add(10)))
    print(sess.run(my_var.assign_sub(2)))

20
18


In [60]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

sess1.close()
sess2.close()

20
8


In [61]:
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(2 * W) # Not safe because W may not be initialized
U = tf.Variable(2 * W.initialized_value()) # Such that W can be initialized in one time

## InteractiveSession

In [62]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(c.eval()) # InteractiveSession makes itself default, it runs sess.run()
sess.close()

30.0


## Control Dependencies
tf.Graph.control_dependencies(control_inputs)

In [63]:
# given graph have 5 ops: a, b, c, d, e
with g.control_dependencies([a, b, c]):
    # d and e will run after a, b, c
    d = ...
    e = ...

NameError: name 'g' is not defined

## Placeholders
can assemble the graph first without knowing the values needed for computation

tf.placeholder(dtype, shape=None, name=None)
- shape=None means it can be any shape

tf.Graph.is_feedable(tensor)

In [66]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = a + b
with tf.Session() as sess:
    print(sess.run(c, {a: [1, 2, 3]})) # put the actual tensor as the key
    
list_of_values_for_a = [[1, 1, 1], [3, 3, 3]]
with tf.Session() as sess:
    for a_value in list_of_values_for_a:
        print(sess.run(c, {a: a_value}))

[6. 7. 8.]
[6. 6. 6.]
[8. 8. 8.]


In [68]:
# Use feed_dict for dynamically feed the data
a = tf.add(2, 3)
b = tf.multiply(a, 3)
with tf.Session() as sess:
    replace_dict = {a: 15}
    print(sess.run(b, feed_dict=replace_dict))

45


## Lazy Loading

In [70]:
# Normal loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # create the node before executing the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./graphs/normal_loading', sess.graph)
    for _ in range(10):
        sess.run(z)
    writer.close()

In [73]:
# Lazy loading
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./graphs/normal_loading', sess.graph)
    for _ in range(10):
        sess.run(tf.add(x, y))
    writer.close()
# In this case, add is called multiple times. Each time creates a new node. It may explode.